name: Publish Docker image to GHCR

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'Dockerfile'
      - '.github/workflows/ghcr-publish.yml'
      - 'entrypoint.sh'
      - 'generateACL.sh'
      - 'dynDNSCron.sh'
      - 'configs/**'
  release:
    types: [ published ]

# Notes:
# - Ensure GHCR is enabled in your org/user settings.
# - Make the package public in: Repository → Settings → Packages → your image → Change visibility to Public.
# - First push may require you to manually flip visibility once, subsequent pushes keep it.

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    name: Build and push image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write  # for provenance/attestations

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # On releases, include semver tags
            type=semver,pattern={{version}},enable=${{ github.event_name == 'release' }}
            type=semver,pattern={{major}}.{{minor}},enable=${{ github.event_name == 'release' }}
            type=semver,pattern={{major}},enable=${{ github.event_name == 'release' }}
            # On master branch, publish latest
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/master' }}
            # Always include the sha tag
            type=sha

      - name: Build and push
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: true

      - name: Print image references
        run: |
          echo "Published tags:"
          echo "${{ steps.meta.outputs.tags }}" | tr ' ' '\n'

      - name: Visibility reminder
        if: github.event_name != 'pull_request'
        run: |
          echo "Package URL: https://ghcr.io/${{ github.repository }}"
          echo "If first publish, go to the package page and set visibility to Public to allow others to pull."